name: CI

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "gurygury/test-hello"
  CONTAINER_NAME: "pocket"
  VERSION: "latest"

jobs:
  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: docker login
  #     env:
  #       DOCKER_LOGIN: ${{secrets.DOCKER_LOGIN}}
  #       DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
  #     run: |
  #       docker login -u $DOCKER_LOGIN -p $DOCKER_TOKEN 
  #   - name: Build the Docker image
  #     run: make build-image
      
  #   - name: Docker Push
  #     run: docker push gurygury/test-hello:latest

  deploy:
    runs-on: ubuntu-latest
    # needs: build_and_push

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASS_PHRASE }}
          envs: IMAGE_NAME,CONTAINER_NAME,VERSION
          script: |
            # Login into Digital Ocean Registry
            docker login -u $DOCKER_LOGIN -p $DOCKER_TOKEN 
            # Stop running container
            docker stop $(echo $CONTAINER_NAME)
            # Remove old container
            docker rm $(echo $CONTAINER_NAME)
            # Run a new container from a new image
            docker run -d \
            --restart always \
            --publish 80:80 \
            --name $(echo $CONTAINER_NAME) \
            $(echo $IMAGE_NAME):$(echo $VERSION)