name: CI

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "gurygury/test-hello"
  CONTAINER_NAME: "pocket"
  VERSION: "latest"

jobs:
  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: make test

      - name: Upload build result
        uses: actions/upload-artifact@v2
        with:
          name: test_cov
          path: ./cover.out.tmp

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_LOGIN: ${{secrets.DOCKER_LOGIN}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: |
        docker login -u $DOCKER_LOGIN -p $DOCKER_TOKEN 
    - name: Build the Docker image
      run: make build-image
      
    - name: Docker Push
      run: docker push $(echo $IMAGE_NAME):$(echo $VERSION)

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to VK Cloud Solutions virtual server via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASS_PHRASE }}
          envs: IMAGE_NAME,CONTAINER_NAME,VERSION
          script: |
            # Login into Docker Hub 
            docker login -u $DOCKER_LOGIN -p $DOCKER_TOKEN 
            # Stop running container
            docker stop $(echo $CONTAINER_NAME)
            # Remove old container
            docker rm $(echo $CONTAINER_NAME)
            # Run a new container from a new image
            docker run -d \
            --restart always \
            --publish 8080:8080 \
            --name $(echo $CONTAINER_NAME) \
            $(echo $IMAGE_NAME):$(echo $VERSION)